name: Android CI

on:
  push:
    branches: [ main, master, work ]
  pull_request:
    branches: [ main, master, work ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
          arguments: assembleDebug

      - name: Build Release APK (unsigned)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
          arguments: assembleRelease

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TaskLock-apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
          if-no-files-found: warn
